# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 440989691f49809ff7f4c9e46982abf04d9beed7840b9277d91ae11bbb9366a37932862044ba7573310ccdaae88b0c53867c56f5e0c5dc7b10b091e50730a899

test:
  secret_key_base: b7a8aa0dc5c25599028da1f9e68442eabd0d0d69648528e3f61ca53dffca2652a189419af5fdd89edd9c38491dcd538d79492aee784b7f047699931b949270ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
